# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# 啟用 OLED 與外部電源
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# 啟用 zmk-nice-oled 的自訂螢幕與 HID 指示燈 (Caps Lock)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_ON=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_ZMK_HID_INDICATORS=y
