# 啟用 OLED 顯示器與外部電源
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# 啟用 zmk-nice-oled 自訂畫面與 Caps Lock 狀態圖示
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_ON=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_ZMK_HID_INDICATORS=y
